const Scheduler = (function() {
const WEIGHT_SCORE = { High: 3, Medium: 2, Low: 1, Unrated: 1.5 };
function daysBetween(a, b) { const ms = new Date(b) - new Date(a); return Math.floor(ms / 86400000); }
function todayStr() { return new Date().toISOString().slice(0, 10); }
function examDateOf(meta) { if (meta.examDate) return meta.examDate; const d = new Date(meta.startDate); d.setDate(d.getDate() + meta.totalDays); return d.toISOString().slice(0, 10); }
function dayNumber(meta) { return Math.max(1, daysBetween(meta.startDate, todayStr()) + 1); }
function daysRemaining(meta) { return Math.max(0, daysBetween(todayStr(), examDateOf(meta))); }
function scoreChapter(chapter, meta) { const w = WEIGHT_SCORE[chapter.weightage] || WEIGHT_SCORE.Unrated; const remaining = daysRemaining(meta); const totalSpan = meta.totalDays || 70; const proximityFactor = 1 + Math.max(0, (totalSpan - remaining) / totalSpan) * 1.5; if (!chapter.lastTouched) { return w * proximityFactor * 4 + 10; } const sinceTouched = daysBetween(chapter.lastTouched, todayStr()); const statusDampMap = { "not-started": 1.3, "in-progress": 1.0, "revised": 0.75, "locked-in": 0.5 }; const statusDamp = statusDampMap[chapter.status] || 1.0; const urgency = 1 + Math.sqrt(Math.max(0, sinceTouched)); return w * proximityFactor * urgency * statusDamp; }
function reasonFor(chapter, meta) { if (!chapter.lastTouched) { return "Never touched - needs a first pass"; } const since = daysBetween(chapter.lastTouched, todayStr()); const wTag = chapter.weightage || "Unrated"; if (since === 0) { return "Touched today - " + wTag + " weightage"; } if (since === 1) { return "Last touched yesterday - " + wTag + " weightage"; } return "Overdue " + since + " days - " + wTag + " weightage"; }
function buildTodayQueue(data, limit) { if (!limit) { limit = 8; } const meta = data.meta; const rows = []; data.subjects.forEach(function(subj) { subj.chapters.forEach(function(ch) { rows.push({ subjectId: subj.id, subjectName: subj.name, chapter: ch, score: scoreChapter(ch, meta), reason: reasonFor(ch, meta) }); }); }); rows.sort(function(a, b) { return b.score - a.score; }); return rows.slice(0, limit); }
function subjectStats(subj) { const total = subj.chapters.length; if (total === 0) { return { total: 0, notStarted: 0, inProgress: 0, revised: 0, lockedIn: 0, pct: 0 }; } const counts = { notStarted: 0, inProgress: 0, revised: 0, lockedIn: 0 }; subj.chapters.forEach(function(ch) { if (ch.status === "not-started") { counts.notStarted++; } else if (ch.status === "in-progress") { counts.inProgress++; } else if (ch.status === "revised") { counts.revised++; } else if (ch.status === "locked-in") { counts.lockedIn++; } }); const pct = Math.round(((counts.revised + counts.lockedIn) / total) * 100); return Object.assign({ total: total, pct: pct }, counts); }
function overallStats(data) { let total = 0; let lockedIn = 0; let revised = 0; let neverTouched = 0; let mcqAtt = 0; let mcqCorrect = 0; let numAtt = 0; let numCorrect = 0; data.subjects.forEach(function(subj) { subj.chapters.forEach(function(ch) { total++; if (ch.status === "locked-in") { lockedIn++; } if (ch.status === "revised") { revised++; } if (!ch.lastTouched) { neverTouched++; } if (ch.practice) { mcqAtt += ch.practice.mcqAttempted || 0; mcqCorrect += ch.practice.mcqCorrect || 0; numAtt += ch.practice.numericalsAttempted || 0; numCorrect += ch.practice.numericalsCorrect || 0; } }); }); const mcqAccuracy = mcqAtt ? Math.round((mcqCorrect / mcqAtt) * 100) : null; const numAccuracy = numAtt ? Math.round((numCorrect / numAtt) * 100) : null; return { total: total, lockedIn: lockedIn, revised: revised, neverTouched: neverTouched, mcqAtt: mcqAtt, mcqCorrect: mcqCorrect, numAtt: numAtt, numCorrect: numCorrect, mcqAccuracy: mcqAccuracy, numAccuracy: numAccuracy }; }
return { todayStr: todayStr, dayNumber: dayNumber, daysRemaining: daysRemaining, examDateOf: examDateOf, scoreChapter: scoreChapter, reasonFor: reasonFor, buildTodayQueue: buildTodayQueue, subjectStats: subjectStats, overallStats: overallStats, daysBetween: daysBetween };
})();
